import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
const HomePage = () => {
  return <div>HomePage</div>;
};

export default HomePage;
